-- local status, mason = pcall(require, 'mason')
-- if (not status) then return end
-- local status, masonlsp = pcall(require, "mason-lspconfig")
-- if (not status) then return end
-- local status, lspconfig = pcall(require, "lspconfig")
-- if (not status) then return end
--
-- mason.setup()
-- masonlsp.setup({
--     ensure_installed = {"sumneko_lua", "pyright", "tsserver", "clangd", "rust-analyzer"}
-- })
--
-- masonlsp.setup_handlers(
--     {
--         function(server)
--         
--         end,
--     }
-- )
